# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5146ee518c21c6e5ad5c789895b285a320fb83091f4d6e43d99da2bdb5b842af07dd03a788bc31d662921c1186b0e499bf214e2c12c78a4877faf1301cdab7d8

test:
  secret_key_base: 95ab030253cfe8e80a88527114604ea189aa2017e6ccbab04c863467ca3a3b7548678c9de5b52a49b3abd2aeaa945a87209021c79dd9f8ebcee8c2327ef06118

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
